language: php
php:
  - 7.2
  - 7.3
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - composer cs-check
  - composer test

after_script:
  - travis_retry php vendor/bin/php-coveralls
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/temp/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
