language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"
before_script:
  - composer self-update
  - composer install --dev
script: phpunit --configuration tests/configuration.xml --coverage-clover tests/clover.xml
after_script:
  - php vendor/bin/coveralls -v
