language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - nightly
  - hhvm

before_script:
  - composer self-update
  - composer install --dev

script: composer test

after_script:
  - php vendor/bin/coveralls -v
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/clover.xml

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: hhvm
